language: php
php:
  - "5.4"
  - "5.3"
before_script:
  - composer install --dev
script:
  - make -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --configuration tests/phpunit.xml tests
after_script:
  - php vendor/bin/coveralls -v
